---
abstract: 'Yars Server'
author:
  - unknown
build_requires:
  Clustericious: 0.97
  Clustericious::Config: 0.07
  Digest::file: 0
  File::Compare: 0
  File::Copy: 0
  File::Find: 0
  File::Find::Rule: 0
  Filesys::Df: 0
  Hash::MoreUtils: 0
  List::MoreUtils: 0
  List::Util: 0
  Mojolicious: 2.62
  Test::More: 0
  Test::Pod::Coverage: 0
  Try::Tiny: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Yars
provides:
  Yars:
    file: lib/Yars.pm
    version: 0.74
  Yars::Routes:
    file: lib/Yars/Routes.pm
    version: 0
  Yars::Tools:
    file: lib/Yars/Tools.pm
    version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.74
