---
abstract: 'Yet Another RESTful-Archive Service'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Capture::Tiny: '0'
  Module::Build: '0.3601'
  Test::Clustericious::Cluster: '0.08'
  Test::Clustericious::Config: '0'
  Test::Clustericious::Log: '0'
  Test::More: '0.94'
  YAML::XS: '0'
  perl: '5.010001'
configure_requires:
  Module::Build: '0.3601'
  perl: '5.010001'
dynamic_config: 1
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Yars
recommends:
  EV: '0'
requires:
  Clustericious: '0.9925'
  Clustericious::Client: '0'
  Clustericious::Client::Command: '0'
  Clustericious::Commands: '0'
  Clustericious::Config: '0.21'
  Clustericious::Log: '0.11'
  Exporter: '0'
  File::Find::Rule: '0'
  File::HomeDir: '0.91'
  Hash::MoreUtils: '0'
  IO::Uncompress::Gunzip: '0'
  JSON::XS: '0'
  List::MoreUtils: '0'
  Log::Log4perl: '0'
  Log::Log4perl::CommandLine: '0'
  Mojo::Asset::File: '0'
  Mojo::URL: '0'
  Mojolicious: '5.48'
  Number::Bytes::Human: '0.09'
  Yars::Client: '0.90'
  base: '0'
  lib: '0'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/plicease/Yars/issues
  homepage: http://perl.wdlabs.com/Yars
  repository: git://github.com/plicease/Yars.git
version: '1.03'
